version: '3'
services: 
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=danglingmind
            - POSTGRES_PASSWORD=#ricky2327
            - POSTGRES_DB=blogapp
        logging:
          options:
            max-size: 10m
            max-file: "3"
        container_name: postgres
        ports:
            - 5432:5432
        volumes: 
            - db-data:/var/lib/postres/data
            # copy table creation scripts
            - ./create-tables-postgres.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks: 
            - overlay

    redis:
        image: redis
        container_name: redis
        ports: 
            - 6379:6379
        networks: 
            - overlay

    backend:
        build: 
            context: .
            dockerfile: Dockerfile.local
        container_name: dmblogs-backend
        ports:
            - "8000:8000"
        env_file: .env_docker
        networks: 
            - overlay
        depends_on: 
            - redis 
            - postgres
        restart: always

volumes:
    db-data:
        external: false

networks:
    overlay: